BDSA-2021/BDSA21-Say-AAAAAA

BDSA2021.sln

Add solution file

---

.github/workflows/build-and-test.yml
.github/workflows/check-formatting.yml

Added a workflow for checking formatting of committed/pull requested code, as well as a workflow that builds and tests committed/pull requested code
- Forcing a semi consistent code style.
- Making sure code pulled into master compiles, and passes unit tests.
Placed the code into a different branch, committed a badly formatted file while making sure the actions worked as expected.

[FEATURE] Workflows

---

BDSA2021.sln
SELearning.Api.Tests/SELearning.Api.Tests.csproj
SELearning.Api/Controllers/WeatherForecastController.cs
SELearning.Api/Program.cs
SELearning.Api/Properties/launchSettings.json
SELearning.Api/SELearning.Api.csproj
SELearning.Api/WeatherForecast.cs
SELearning.Api/appsettings.Development.json
SELearning.Api/appsettings.json
SELearning.Core/README.md
SELearning.Core/SELearning.Core.csproj
SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
SELearning.Infrastructure/README.md
SELearning.Infrastructure/SELearning.Infrastructure.csproj

Scaffolded a few different projects, using the structure Rasmus taught, and added necessary references between the projects. The projects are:
- SELearning.Core
- SELearning.API
- SELearning.API.Tests
- SELearning.Infrastructure
- SELearning.Infrastructure.Tests

[FEATURE] Scaffolded Core, API, Infrastructure

---

.gitignore
SELearning.Core/Permission/IPermissionService.cs
SELearning.Core/Permission/Permission.cs
SELearning.Core/Permission/PermissionDecider.cs
SELearning.Core/Permission/Rule.cs
SELearning.Infrastructure.Tests/Permission/PermissionDeciderTests.cs

This is an implementation of the initial permission service. There are still some missing pieces of how we inject this into the authorization policy system made by microsoft... but that is part 2.
This change is necessary in order to fulfill our goal of delivering a solution that works... so please approve :-)
This does not fix any issues, however it is an implementation step for #15. 
This has been tested by unittests in the SELearning.Infrastructure.Tests project.

[FEATURE] Implement permission service

---

SELearning.Core/CredibilityRepository.cs
SELearning.Core/User.cs
SELearning.Core/services/CredibilityService.cs
SELearning.Infrastructure.Tests/GlobalUsings.cs
SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
SELearning.Infrastructure.Tests/services/CredibilityCalculatorTests.cs
SELearning.Infrastructure/services/CredibilityCalculator.cs

Adds the credibility subsystem specified in #11.
To code the project, my friend!
Unit testing of `CredibilityCalculator` using a `Mock` of `ICredibilityRepository`.

[FEATURE] Add credibility service

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/mssql/installSQLtools.sh
.devcontainer/mssql/postCreateCommand.sh
.vscode/settings.json

Adds VS Code devcontainer. Read about devcontainers at: https://code.visualstudio.com/docs/remote/containers.

[META] Add VS Code devcontainer

---

README.md
SELearning.Infrastructure.Tests/Authorization/AuthorizePermissionAttributeTests.cs
SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
SELearning.Infrastructure.Tests/Authorization/PermissionPolicyProviderTests.cs
SELearning.Infrastructure/Authorization/AuthorizationConstants.cs
SELearning.Infrastructure/Authorization/AuthorizePermissionAttribute.cs
SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
SELearning.Infrastructure/Authorization/CredibilityPermissionRequirement.cs
SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs

This is an implementation to have a 'or' evaluation of the permissions.

[FEATURE] Authorization 'or' evaluation of credibility permissions

---

SELearning.API/Controllers/CommentController.cs
SELearning.API/Controllers/ContentController.cs
SELearning.API/Program.cs
SELearning.Infrastructure/Authorization/AuthorizationConfiguration.cs

[FIX] Make master runnable

---

SELearning.Core/Permission/IAuthored.cs
SELearning.Core/Permission/Permission.cs
SELearning.Infrastructure.Tests/Authorization/AuthoredCredibilityAuthorizationHandlerTests.cs
SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
SELearning.Infrastructure/Authorization/AuthoredCredibilityAuthorizationHandler.cs
SELearning.Infrastructure/Authorization/AuthorizationConfiguration.cs
SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
SELearning.Infrastructure/Authorization/CredibilityPermissionRequirement.cs
SELearning.Infrastructure/Authorization/IAuthored.cs
SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs

Is an authorization handler logic based on if the user i allowed to edit a specific ressource.
Because we want to limit what the user should have access to.
We have tried it with a locally created test controller.

Resource based authorization

---

SELearning.API/Controllers/CommentController.cs
SELearning.API/Controllers/ContentController.cs
SELearning.API/Controllers/SectionController.cs
SELearning.Core/Permission/Permission.cs
SELearning.Infrastructure.Tests/Authorization/PermissionPolicyProviderTests.cs
SELearning.Infrastructure/Authorization/AuthorizePermissionAttribute.cs
SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs

To make stuff work, we used some truly forbidden magic strings. I am fixing that here by using enum variants to generate the policy name strings.
Magic can sometimes be a curse.
Unit tests

Refactor authorization

---

SELearning/Pages/AllContent.razor

[FIX] Fixed the all content page

---

SELearning/Shared/Content/ContentTile.razor

[FIX] Show content author instead of user class name

---

SELearning.Core/Permission/PermissionCredibilityService.cs

The cred scores have been changed in order to make it easier for us to do a video presentation. Now we can show the system's features without having to up- or downvote more than a few times.
All unit tests still pass.

Change cred scores

---

SELearning.Core/Content/Section.cs
SELearning.Infrastructure/ContentRepository.cs

No longer embed Section.Content in ContentDTO to avoid recursion.

[FIX] Fixed recursion error

---

SELearning.API/Program.cs

This is so the we don't instantiate a lot of connection to the database when handling a single request. With the default lifecycle scoped, it now only instanciates one single connection per request

Rollback dbcontext lifecycle

---

SELearning/Pages/Content.razor
SELearning/Pages/CreateContent.razor
SELearning/Pages/CreateSection.razor
SELearning/Shared/Comment/CommentSection.razor
SELearning/Shared/Comment/CommentTile.razor
SELearning/Shared/Content/ContentTile.razor
SELearning/Shared/Section/SectionTile.razor
SELearning/Shared/Toast/ToastNotification.cs
SELearning/Shared/Toast/ToastWrapper.razor

This, but repeated for every action that can give unauthorized:

Add fitting toast messages for unauthorized actions

---

SELearning/Shared/Comment/CommentSection.razor
SELearning/Shared/Comment/CommentTile.razor

Call OnCommentDelete

---

SELearning.Infrastructure.Tests/Section/SectionManagerTests.cs
SELearning.Infrastructure.Tests/Section/SectionRepositoryTests.cs
SELearning.Infrastructure/SectionRepository.cs

All Tests fixed

---

SELearning.API.Tests/UserControllerTests.cs
SELearning.API/Controllers/UserController.cs
SELearning.Core/User/UserDTO.cs
SELearning.Infrastructure.Tests/User/UserRepositoryTests.cs
SELearning.Infrastructure.Tests/User/UserTests.cs
SELearning/Shared/LoginDisplay.razor

Created tests for the user infrastructure, and added a CredibilityUserDTO, as well as used it on the frontend.

[FEATURE] User tests

---

SELearning/Shared/Comment/CommentTile.razor

Make comment rating change on rate

---

.gitattributes
.github/workflows/build-and-deploy.yml
README.md
docker-compose.dev.yml
docker-compose.prod.yml
docs/manual-setup.md
scripts/Dockerfile.db
scripts/Dockerfile.dev
scripts/Dockerfile.prod
scripts/docker-compose-init.ps1
scripts/docker-compose-init.sh
scripts/entrypoint.dev.sh
scripts/entrypoint.prod.sh
scripts/shared.sh

- Created a docker-compose.dev.yml file for quick builds
- Explained the new setup in README.md
- Moved manual setup to its own file
- Refactored the docker-compose-init.sh script

[FEATURE] Dev compose
